clear;

% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by NPRTOOL
% Created Sat Apr 04 10:10:24 CEST 2015
%
% This script assumes these variables are defined:
%
%   irisInputs - input data.
%   irisTargets - target data.

load('dane.mat');

a = 1;
b = 150;
r = (b-a).*rand(100,1) + a;

nr_obs=30:130;
inputs = irisInputs;
inputsProd = irisInputs(:,nr_obs);
targets = irisTargets;
targetsProd = irisTargets(:,nr_obs);

% Create a Pattern Recognition Network
hiddenLayerSize1 = 15;
hiddenLayerSize2 = 5;
layers=[hiddenLayerSize1 hiddenLayerSize2];
% net = patternnet(hiddenLayerSize);
net = feedforwardnet(layers);


% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = .6;
net.divideParam.valRatio = .1;
net.divideParam.testRatio = .3;


% Train the Network
[net,tr] = train(net,inputs,targets);

% Czêœæ Produkcyjna
outputsProd = sim(net,inputsProd);
%outputsProd = net(inputsProd);
errors = gsubtract(targetsProd,outputsProd);
errors = round(errors)
performance = perform(net,targetsProd,outputsProd)
outputsProd= round(outputsProd);

% View the Network
view(net);

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
figure, plotconfusion(targetsProd,outputsProd);
%figure, ploterrhist(errors)
