clear;

% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by NPRTOOL
% Created Sat Apr 04 10:10:24 CEST 2015
%
% This script assumes these variables are defined:
%
%   irisInputs - input data.
%   irisTargets - target data.

load('dane.mat');

a = 1;
b = 150;
r = (b-a).*rand(100,1) + a;
r = uint8(r);

inputsTrain = irisInputs(:,r);
targetsTrain = irisTargets(:,r);

a = 1;
b = 150;
r = (b-a).*rand(150,1) + a;
r = uint8(r);

inputsTest = irisInputs(:,r);
targetsTest = irisTargets(:,r);

% Start od jednego neuronu, krok +1 neuron, do 35 neuronów
start=1;
krok=1;
do=20;

wyniki = zeros(do,3);

for i=start:krok:do

% Create a Pattern Recognition Network
hiddenLayerSize = i;
%layers=[15 10];
%net = feedforwardnet(layers);
net = patternnet(hiddenLayerSize);

%net = patternnet(hiddenLayerSize);


% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = .7;
net.divideParam.valRatio =   .3;

net.trainParam.showWindow=0; % ukrywanie okna sieci nurnowej podczas uczenia

% Train the Network
[net,tr] = train(net,inputsTrain,targetsTrain);

% Czêœæ TESTOWA
outputs = net(inputsTest);
errors = gsubtract(targetsTest,outputs);
errors = round(errors);
MSE = perform(net,targetsTest,outputs);
outputs = round(outputs);

[c,cm] = confusion(targetsTest,outputs); % macierz kontyngencji
c =  1-sum(diag(cm))/ sum(sum(cm)); % odstek b³êdnych klasyfikacji

wyniki(i,1) = i;
wyniki(i,2) = c;
wyniki(i,3) = MSE;

end

save('net.mat','net');

wyniki

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, plotconfusion(targets,outputs)
%figure, ploterrhist(errors)
